### PR TITLE
Fixed errors with relative coords and scaling

### PR DESCRIPTION
**Pull request by hadron137**
* Added support for SVG matrix transformations (only translate and scale, not rotation)
* Automatically flatten Bézier curves (much better to do it in InkScape, but at least now it won't scribble everywhere if one is encountered).
* Remove successive duplicate points (sometimes InkScape repeats the final point)
* Expanded logfile output

### CODE REVIEW

**Review by cmonr — APPROVED** [review]
Nice!

**Comment by cmonr** [comment]
Wow, never expected for this script to see a PR!

> Expanded logfile output

Do you have an example before and after for this part?

**Comment by hadron137** [comment]
These attached PNG images show the comparison. The figure on the left is
with the previous code, the figure on the right is with my new code.

The raw SVG files are also attached, for your reference.

**Comment by hadron137** [comment]
Example logfile attached.

**Comment by cmonr** [comment]
Hmm.
@hadron137 do you think you could try using the GitHub interface? Not sure the email attachments came through.

**Comment by hadron137** [comment]
Sure, I'll send it tomorrow...

**Comment by cmonr** [comment]
Thanks @hadron137!

**Pull request merged**
